export const PROVIDER_INITIALIZING = 'PROVIDER_INITIALIZING';
export const PROVIDER_INITIALIZED = 'PROVIDER_INITIALIZED';
export const PROVIDER_AUTHENTICATING = 'PROVIDER_AUTHENTICATING';
export const PROVIDER_AUTHENTICATED = 'PROVIDER_AUTHENTICATED';
export const FIREBASE_AUTHENTICATING = 'FIREBASE_AUTHENTICATING';
export const FIREBASE_AUTHENTICATED = 'FIREBASE_AUTHENTICATED';

export const INITIALIZATION_ERROR = 'INITIALIZATION_ERROR';
export const AUTHENTICATION_DONE = 'AUTHENTICATION_DONE';
export const AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
